### ISSUE TITLE
Slather failing

### ISSUE THREAD

**Issue by andreamazz** [andreamazz/AMPopTip#43]
From the latest travis builds:
```
$ slather
Slathering...
/Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/lib/slather/project.rb:50:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/lib/slather/coverage_service/coveralls.rb:76:in `coveralls_coverage_data'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/lib/slather/coverage_service/coveralls.rb:129:in `post'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/bin/slather:72:in `post'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/bin/slather:40:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/gems/slather-1.8/bin/slather:6:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/bin/slather:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/bin/slather:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.0.0-p481/bin/ruby_executable_hooks:15:in `<main>'
```

Looks like that Slather is failing even if the setup was performed (it was working before after all).  

Any idea is welcome :grin:

**Comment by andreamazz** [comment]
Switched to codecov.io
